name: Daily deploy to Cloudflare Pages

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点运行
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Workers deploy hook
        run: |
          curl -X POST "${{ secrets.CF_WORKERS_DEPLOY_HOOK }}"